repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.1  # Check for latest version
    hooks:
      - id: sqlfluff-fix
        args: ["--dialect", "postgres"]  # Change for Snowflake, BigQuery, etc.
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']