name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Create profiles.yml
        run: |
          mkdir -p /home/runner/.dbt
          echo "Creating profiles.yml..."
          cat <<EOF > /home/runner/.dbt/profiles.yml
          cmhlp:
            outputs:
              dev:
                dbname: "{{ env_var('POSTGRES_DBNAME') }}"
                host: "{{ env_var('POSTGRES_HOST') }}"
                password: "{{ env_var('POSTGRES_PASSWORD') }}"
                port: 5432
                schema: dev
                threads: 8
                type: postgres
                user: "{{ env_var('POSTGRES_USER') }}"
            target: dev
          EOF
          echo "profiles.yml created successfully."
          ls -al /home/runner/.dbt

      # - name: Check warehouse connection
      #   run: dbt debug

      - name: Install dbt dependencies
        run: dbt deps

      # - name: dbt build
      #   run: dbt build --full-refresh
      #   env:
      #     POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
      #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_HOST: 127.0.0.1
      #     DBT_PROFILES_DIR: /home/runner/.dbt

      - name: Benchmarking models
        run: sqlfluff lint models --bench
        env:
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: 127.0.0.1

      - name: Lint models
        run: sqlfluff lint models -f human
        env:
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: 127.0.0.1