name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create profiles.yml
        run: |
          mkdir -p /home/runner/.dbt
          echo "Creating profiles.yml..."
          cat <<EOF > /home/runner/.dbt/profiles.yml
          cmhlp:
            outputs:
              dev:
                type: postgres
                dbname: ${{ secrets.POSTGRES_DBNAME }}
                host: 127.0.0.1
                password: ${{ secrets.POSTGRES_PASSWORD }}
                port: 5432
                schema: dev
                threads: 4
                user: ${{ secrets.POSTGRES_USER }}
            target: dev
          EOF
          echo "profiles.yml created successfully."
          ls -al /home/runner/.dbt

      - name: Open SSH Tunnel
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 500s
          port: 22
          script: |
            echo "Creating SSH tunnel..."
            echo ${{ secrets.POSTGRES_HOST }}
            ssh -N -f 5432:${{ secrets.POSTGRES_HOST }}:5432 ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVERIP }}

      - name: Check warehouse connection
        run: dbt debug

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: dbt build
        run: dbt build --full-refresh
        env:
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: 127.0.0.1
          DBT_PROFILES_DIR: /home/runner/.dbt

      - name: Lint models
        run: sqlfluff lint models --bench -f human
        env:
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: 127.0.0.1