version: 2
sources:
- name: mehsana
  schema: staging_mehsana
  tables:
    - name: zzz_case
      identifier: zzz_case
      description: 
        This table contains the data of all cases in the CommCare application. Each update to a case \
        is recorded as a new entry and the latest entry is the most recent update
    - name: champion_training_form
      identifier: Champion_Training_Details__CHT_
      description: This table contains the details of the training sessions attended by the champions
    - name: refresher_champion_training_form
      identifier: Refresher_Training_Details
      description: This is form to capture the details of the refresher training sessions attended by the champions
- name: patan
  schema: staging_patan
  tables:
    - name: zzz_case
      identifier: zzz_case
      description: 
        This table contains the data of all cases in the CommCare application. Each update to a case \
        is recorded as a new entry and the latest entry is the most recent update
    - name: champion_training_form
      identifier: Champion_Training_Details__CHT_
      description: This table contains the details of the training sessions attended by the champions
    - name: refresher_champion_training_form
      identifier: Refresher_Training_Details
      description: This is form to capture the details of the refresher training sessions attended by the champions
- name: sabarkantha
  schema: staging_sabarkantha
  tables:
    - name: zzz_case
      identifier: zzz_case
      description: 
        This table contains the data of all cases in the CommCare application. Each update to a case \
        is recorded as a new entry and the latest entry is the most recent update
    - name: champion_training_form
      identifier: Champion_Training_Details__CHT_
      description: This table contains the details of the training sessions attended by the champions
    - name: refresher_champion_training_form
      identifier: Refresher_Training_Details
      description: This is form to capture the details of the refresher training sessions attended by the champions
- name: org
  schema: staging_org
  tables:
    - name: location
      identifier: location
      description: 
        This table contains the details of all locations in the CommCare application.
    - name: location_type
      identifier: location_type
      description: 
        This table contains the details of all location types in the CommCare application.
  